---
- name: Install Jenkins
  hosts: jenkins
  become: true
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: keys/servers/centos.pem
  roles:
    - role: geerlingguy.epel
    - role: geerlingguy.nginx
    - role: nodejs
      vars:
        - nodejs_npm_global_packages:
            - pm2
            - serverless
            - gulp
            - "@angular/cli"
            - "@babel/cli"
            - webpack
            - webpack-cli
            - webpack-dev-servers
            - react-scripts
        - nodejs_links:
            - pm2
            - serverless
            - gulp
            - ng
            - babel
            - webpack
            - webpack-cli
            - webpack-dev-servers
            - react-scripts
    - role: pulumi
      vars:
        - noncompliant.pulumi_token: pul-4764sdfkh34wd584754569665633
    - role: git_config
    - role: nginx_config
      vars:
        - secure: true
        - web_directory_owner: nginx
        - with_default_conf: true
    - role: geerlingguy.remi
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: php_composer
    - role: nginx_domains
      vars:
        - subdomains_folder: jenkins/
        - subdomains:
            - jenkins.demo.com
    - role: java
    - role: jenkins
