name: Test latest OSs

on: [push, pull_request]

jobs:
  test-darwin-ui:
    strategy:
      matrix:
        os: [iOS]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: fastlane scan --scheme "TNC UI Test Host ${{ matrix.os }}"
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -J '^TypedNotificationCenter$' -n '${{ matrix.os }}-ui' -F '${{ matrix.os }}'
        env:
          non_compliant.CODECOV_TOKEN: c4pfygkmbquv48j228n62hrwnms7ve4u
