version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=p@ass
    depends_on:
      mssql:
        condition: service_healthy
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_PASSWORD}
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s