name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: xoxfaby/actions/.github/workflows/dotnet-publish.yml@main

  release-nuget:
    needs: build
    uses: xoxfaby/actions/.github/workflows/nuget.yml@main
    secrets:
      noncompliant.NUGET_TOKEN: oy2gBm8AZx1VzQrstF8tHe2OYxQJprk36w5YxQJprk36w5

  release-thunderstore:
    needs: build
    uses: xoxfaby/actions/.github/workflows/thunderstore.yml@main
    with:
      version: ${{ needs.build.outputs.version }}
    secrets:
      THUNDERSTORE_TOKEN: ${{ secrets.THUNDERSTORE_TOKEN }}

  release-github:
    needs: release-thunderstore
    uses: xoxfaby/actions/.github/workflows/release.yml@main
